### ISSUE TITLE
Test validation is too strict when using JMockit

### ISSUE THREAD

**Issue by aleph-zero** [randomizedtesting/randomizedtesting#200]
There are a number of pre-test validations that get run to check that test methods conform to JUnit best practices. One of these is Validation.hasArgsCount().  This method is always called with an argument of zero as in RandomizedRunner.validateTarget():

```
Validation.checkThat(m)
          .describedAs("@ParametersFactory method " + suiteClass.getName() + "#" + m.getName())
          .isStatic()
          .isPublic()
          .hasArgsCount(0)
          .hasReturnType(Iterable.class);
```

The problem with this is that JMockit wants tests to have ```@Injectable``` method parameters:

```
@Test
public void someTestMethod(@Injectable("true") boolean flag, @Injectable("Mary") String name) {
}
```

I propose to add a new ```SYSPROP_NON_STRICT``` that would be lenient in checks such as hasArgsCount(). 

Before I submit a patch, I'd like to know if this would be a non-starter, or if it is something that would be well-received.

**Comment by dweiss** [comment]
Wait... but this validation applies only to methods annotated with ParametersFactory (which are static and invoked by the runner, so they should have zero arguments?).

Could you provide a small code sample or at least a full stack trace of what's happening?

**Comment by aleph-zero** [comment]
I believe this is the actual code snippet that is causing my tests to fail: RandomizedRunner:1660-1665:

```
      // * method()
      Validation.checkThat(method)
        .describedAs("Test method " + suiteClass.getName() + "#" + method.getName())
        .isPublic()
        .isNotStatic()
        .hasArgsCount(0);
```

The stack trace is:
```
java.lang.RuntimeException: Test method com.foo.MyTest#testFoo should have 0 parameters and has these: [class com.foo.X, class com.foo.Y]
	at com.carrotsearch.randomizedtesting.Validation$MethodValidation.hasArgsCount(Validation.java:36)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.validateTestMethods(RandomizedRunner.java:1665)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.collectTestCandidates(RandomizedRunner.java:1309)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.<init>(RandomizedRunner.java:392)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:31)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Where the test method has this signature:
```
 @Test
  public void testFoo(@mockit.Injectable final X x, @mockit.Injectable final Y y) throws Throwable;
```

Ideally I would re-factor the tests so as not to have the injected method parameters, but it is a large, shared code-base and I cannot do that.

**Comment by dweiss** [comment]
And how does that work with plain JUnit? I am not familiar with mockit, but it seems it must be using a custom runner in order to inject those arguments. If it does, then there will be no way of running both randomized testing and mockit together (because they're two different runners).  

This isn't a bug, relaxing those assumptions won't help you (I think).

**Comment by dweiss** [comment]
http://jmockit.org/gettingStarted.html
{code}
When using JUnit 4.5+, verify that jmockit.jar (or the equivalent Maven dependency) appears before JUnit in the classpath. Alternatively, annotate test classes with @RunWith(JMockit.class). 
{code}

You won't be able to run both JMockit and randomized testing. Like I said -- these are two different runners.

**Comment by dweiss** [comment]
It's even worse than that -- they do all sorts of trickery:
{code}
Premain-Class: mockit.internal.startup.Startup
Agent-Class: mockit.internal.startup.Startup
Can-Redefine-Classes: true
Can-Retransform-Classes: true
{code}
plus an "override" of the default Runner:
{code}
package org.junit.runner;
// ...
public abstract class Runner implements Describable {
      static { mockit.internal.startup.Startup.initializeIfPossible(); }
// ...
{code}

I honestly don't think this is going to work. Fork the project, remove the assertion above and keep experimenting. This assertion checks a *valid* JUnit contract (methods shouldn't have parameters). I can't remove it for everyone just for JMockit.

An alternative may be to use:

https://github.com/randomizedtesting/randomizedtesting/blob/master/examples/maven/src/main/java/com/carrotsearch/examples/randomizedrunner/Test007ParameterizedTests.java

but I agree it's far from perfect (but is "JUnit-compatible").
