### ISSUE TITLE
Static leak detector should print the "original" field in the test class that lead to ram usage tester failure

### ISSUE THREAD

**Issue by uschindler** [randomizedtesting/randomizedtesting#227]
While porting Lucene tests to Java 9 module system, the static leak detector made some problems, because it tried to measure objects which are no longer reachable as encapsulated by the Java 9 module system.

But also in previous Java versions some classes referred to by static fields may not be measured, if a security manager is active and accessClassInPackage permission is not given.

Unfortunetely the error message on a `SecurityException` or `InaccessibleObjectException` (new in Java 9) does not really help to identify the static field in the test class. So it is hard to figure out which static field needs to be nulled.

I suggest to keep track on the field name in the test class before diving into the hierarchy behind a field. If during RAM usage measurement some exception occurs, the original field name should be printed as a new exception with the cause that lead to measurement error.

In addition, we should maybe add some automatic checks (based on code in forbiddenapis code that checks the module behind a class - we can only measure objects that are in `java.*` modules) that finds out if a class is encapsulated by Java 9 or hidden by security manager and don't measure it at all (just assigne some static "size" to instances without looking into them).

**Comment by uschindler** [comment]
Here are some examples I found yesterday: https://github.com/apache/lucene-solr/commit/d0156b1126f094e4e469172d55842ed77cb82943

Stack trace was:
```
java.lang.IllegalStateException: Unable to access 'private final java.lang.reflect.Layer java.lang.reflect.Module.layer' to estimate memory usage
	at __randomizedtesting.SeedInfo.seed([1959EA728A13EC78]:0)
	at com.carrotsearch.randomizedtesting.rules.RamUsageEstimator.createCacheEntry(RamUsageEstimator.java:602)
	at com.carrotsearch.randomizedtesting.rules.RamUsageEstimator.measureSizeOf(RamUsageEstimator.java:545)
	at com.carrotsearch.randomizedtesting.rules.RamUsageEstimator.sizeOfAll(RamUsageEstimator.java:387)
	at com.carrotsearch.randomizedtesting.rules.StaticFieldsInvariantRule$1.afterAlways(StaticFieldsInvariantRule.java:127)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at java.lang.Thread.run(java.base@9-ea/Thread.java:804)
Caused by: java.lang.reflect.InaccessibleObjectException: Cannot make a non-public member of class java.lang.reflect.Module accessible
	at sun.reflect.Reflection.throwInaccessibleObjectException(java.base@9-ea/Reflection.java:420)
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@9-ea/AccessibleObject.java:190)
	at java.lang.reflect.Field.checkCanSetAccessible(java.base@9-ea/Field.java:170)
	at java.lang.reflect.Field.setAccessible(java.base@9-ea/Field.java:164)
	at com.carrotsearch.randomizedtesting.rules.RamUsageEstimator$3.run(RamUsageEstimator.java:597)
	at com.carrotsearch.randomizedtesting.rules.RamUsageEstimator$3.run(RamUsageEstimator.java:594)
	at java.security.AccessController.doPrivileged(java.base@9-ea/Native Method)
	at com.carrotsearch.randomizedtesting.rules.RamUsageEstimator.createCacheEntry(RamUsageEstimator.java:594)
	... 13 more
```
If the leak detector would have printed those static fields as failing (actually SolrClients that referred to some internal JVM objects deep in hierrachy. The `layer` field does not really help.

Another one that also failed with Java 8 by @hossman:
https://issues.apache.org/jira/browse/LUCENE-7132?focusedCommentId=15222996&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15222996

The issue was a non-null IndexWriter. If the leak detector would have printed that the "writer" failed to be measured, it would have been easier to find this.

**Comment by uschindler** [comment]
I created PR: #228

**Comment by uschindler** [comment]
Now the PR is ready. I squashed the commits already.

**Comment by dweiss** [comment]
Thanks Uwe!
